repos:
  - repo: https://github.com/mauvehed/trackerstatus
    rev: ''
    hooks:
      - id: poetry-check
      - id: poetry-lock
	  - id: poetry-export
	    args: ["-f", "requirements.txt", "-o", "requirements.txt"]

