name: Branch Protection

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-branch-protection:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch protection
        uses: actions/github-script@v7
        with:
          script: |
            const branch = context.ref.replace('refs/heads/', '');
            const { data: branchProtection } = await github.rest.repos.getBranchProtection({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: branch
            });
            
            if (!branchProtection.required_status_checks) {
              core.setFailed('Branch protection is not properly configured. Required status checks are missing.');
            }
            
            if (!branchProtection.enforce_admins) {
              core.setFailed('Branch protection is not properly configured. Admin enforcement is disabled.');
            }
            
            if (!branchProtection.required_pull_request_reviews) {
              core.setFailed('Branch protection is not properly configured. Pull request reviews are not required.');
            } 